// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateSnippet(ctx context.Context, arg CreateSnippetParams) (int32, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetPasswordByID(ctx context.Context, id int32) (string, error)
	GetSnippetNotExpired(ctx context.Context, id int32) (Snippet, error)
	GetTenLatestSnippets(ctx context.Context) ([]Snippet, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	IsUserExist(ctx context.Context, id int32) (bool, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
